
import java.awt.Font;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ladpa
 */
public class jfrmG2U3 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jfrmG2U3.class.getName());

    /**
     * Creates new form jfrmG2U3
     */
    public jfrmG2U3() {
        initComponents();
        this.setSize(500, 300);
        this.setTitle("Editor");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jbtCortar = new javax.swing.JButton();
        jbtCopiar = new javax.swing.JButton();
        jbtPegar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtaEditor = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jmItemSalir = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmItemCortar = new javax.swing.JMenuItem();
        jmItemCopiar = new javax.swing.JMenuItem();
        jmItemPegar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jmItemF = new javax.swing.JMenuItem();
        jmItemX = new javax.swing.JMenuItem();
        Predeterminada = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jmItem10 = new javax.swing.JMenuItem();
        jmItem12 = new javax.swing.JMenuItem();
        jmItem14 = new javax.swing.JMenuItem();
        jmItem16 = new javax.swing.JMenuItem();
        jmItem20 = new javax.swing.JMenuItem();
        jmItem24 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jmItemNegro = new javax.swing.JMenuItem();
        jmItemRojo = new javax.swing.JMenuItem();
        jmItemAzul = new javax.swing.JMenuItem();
        jmItemVerde = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jmItemNegrita = new javax.swing.JMenuItem();
        jmItemCursiva = new javax.swing.JMenuItem();
        jmItemSubrayado = new javax.swing.JMenuItem();
        jmItemSinEstilo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jbtCortar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tijeras.png"))); 
        jbtCortar.setToolTipText("Cortar");
        jbtCortar.setFocusable(false);
        jbtCortar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtCortar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtCortar.addActionListener(this::jbtCortarActionPerformed);
        jToolBar1.add(jbtCortar);

        jbtCopiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pegar.png"))); 
        jbtCopiar.setToolTipText("Copiar");
        jbtCopiar.setFocusable(false);
        jbtCopiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtCopiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtCopiar.addActionListener(this::jbtCopiarActionPerformed);
        jToolBar1.add(jbtCopiar);

        jbtPegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/guardar.png")));
        jbtPegar.setToolTipText("Pegar");
        jbtPegar.setFocusable(false);
        jbtPegar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtPegar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtPegar.addActionListener(this::jbtPegarActionPerformed);
        jToolBar1.add(jbtPegar);

        jtxtaEditor.setColumns(20);
        jtxtaEditor.setRows(5);
        jScrollPane1.setViewportView(jtxtaEditor);

        jMenu2.setText("Archivo");

        jmItemSalir.setText("Salir");
        jmItemSalir.addActionListener(this::jmItemSalirActionPerformed);
        jMenu2.add(jmItemSalir);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Edicion");

        jmItemCortar.setText("Cortar");
        jmItemCortar.addActionListener(this::jmItemCortarActionPerformed);
        jMenu1.add(jmItemCortar);

        jmItemCopiar.setText("Copiar");
        jmItemCopiar.addActionListener(this::jmItemCopiarActionPerformed);
        jMenu1.add(jmItemCopiar);

        jmItemPegar.setText("Pegar");
        jmItemPegar.addActionListener(this::jmItemPegarActionPerformed);
        jMenu1.add(jmItemPegar);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Opciones");

        jMenu4.setText("Fuente");

        jmItemF.setText("Arial");
        jmItemF.setToolTipText("");
        jmItemF.addActionListener(this::jmItemFActionPerformed);
        jMenu4.add(jmItemF);

        jmItemX.setText("Courier new");
        jmItemX.addActionListener(this::jmItemXActionPerformed);
        jMenu4.add(jmItemX);

        Predeterminada.setText("Predeterminada");
        Predeterminada.addActionListener(this::PredeterminadaActionPerformed);
        jMenu4.add(Predeterminada);

        jMenu3.add(jMenu4);

        jMenu5.setText("Tamaño");

        jmItem10.setText("10");
        jmItem10.addActionListener(this::jmItem10ActionPerformed);
        jMenu5.add(jmItem10);

        jmItem12.setText("12");
        jmItem12.addActionListener(this::jmItem12ActionPerformed);
        jMenu5.add(jmItem12);

        jmItem14.setText("14");
        jmItem14.addActionListener(this::jmItem14ActionPerformed);
        jMenu5.add(jmItem14);

        jmItem16.setText("16");
        jmItem16.addActionListener(this::jmItem16ActionPerformed);
        jMenu5.add(jmItem16);

        jmItem20.setText("20");
        jmItem20.addActionListener(this::jmItem20ActionPerformed);
        jMenu5.add(jmItem20);

        jmItem24.setText("24");
        jmItem24.addActionListener(this::jmItem24ActionPerformed);
        jMenu5.add(jmItem24);

        jMenu3.add(jMenu5);

        jMenu6.setText("Color de fuente");

        jmItemNegro.setText("Negro");
        jmItemNegro.addActionListener(this::jmItemNegroActionPerformed);
        jMenu6.add(jmItemNegro);

        jmItemRojo.setText("Rojo");
        jmItemRojo.addActionListener(this::jmItemRojoActionPerformed);
        jMenu6.add(jmItemRojo);

        jmItemAzul.setText("Azul");
        jmItemAzul.addActionListener(this::jmItemAzulActionPerformed);
        jMenu6.add(jmItemAzul);

        jmItemVerde.setText("Verde");
        jmItemVerde.addActionListener(this::jmItemVerdeActionPerformed);
        jMenu6.add(jmItemVerde);

        jMenu3.add(jMenu6);

        jMenu7.setText("Estilo de fuente");

        jmItemNegrita.setText("Negrita");
        jmItemNegrita.addActionListener(this::jmItemNegritaActionPerformed);
        jMenu7.add(jmItemNegrita);

        jmItemCursiva.setText("Cursiva");
        jmItemCursiva.addActionListener(this::jmItemCursivaActionPerformed);
        jMenu7.add(jmItemCursiva);

        jmItemSubrayado.setText("Subrayado");
        jmItemSubrayado.addActionListener(this::jmItemSubrayadoActionPerformed);
        jMenu7.add(jmItemSubrayado);

        jmItemSinEstilo.setText("Sin Estilo");
        jmItemSinEstilo.addActionListener(this::jmItemSinEstiloActionPerformed);
        jMenu7.add(jmItemSinEstilo);

        jMenu3.add(jMenu7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }

    private void jbtCortarActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtaEditor.cut();
    }

    private void jbtCopiarActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtaEditor.copy();
    }

    private void jbtPegarActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtaEditor.paste();
    }

    private void jmItemSalirActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }
    private void jmItemCortarActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtaEditor.cut();
    }

    private void jmItemCopiarActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtaEditor.copy();
    }

    private void jmItemPegarActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtaEditor.paste();
    }

    private void jmItemFActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtaEditor.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 12));
    }

    private void jmItemXActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtaEditor.setFont(new java.awt.Font("Courier New", java.awt.Font.BOLD, 12));
    }

    private void PredeterminadaActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtaEditor.setFont(new java.awt.Font("Calibri", java.awt.Font.BOLD, 12));
    }

    private void jmItem10ActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtaEditor.setFont(new java.awt.Font("Calibri", java.awt.Font.BOLD, 10));
    }

    private void jmItem12ActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtaEditor.setFont(new java.awt.Font("Calibri", java.awt.Font.BOLD, 12));
    }

    private void jmItem14ActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtaEditor.setFont(new java.awt.Font("Calibri", java.awt.Font.BOLD, 14));
    }

    private void jmItem16ActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtaEditor.setFont(new java.awt.Font("Calibri", java.awt.Font.BOLD, 16));
    }

    private void jmItem20ActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtaEditor.setFont(new java.awt.Font("Calibri", java.awt.Font.BOLD, 20));
    }

    private void jmItem24ActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtaEditor.setFont(new java.awt.Font("Calibri", java.awt.Font.BOLD, 24));
    }

    private void jmItemNegroActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtaEditor.setForeground(java.awt.Color.BLACK);
    }

    private void jmItemRojoActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtaEditor.setForeground(java.awt.Color.RED);
    }

    private void jmItemAzulActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtaEditor.setForeground(java.awt.Color.BLUE);
    }

    private void jmItemVerdeActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtaEditor.setForeground(java.awt.Color.GREEN);
    }

    private void jmItemNegritaActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtaEditor.setFont(new java.awt.Font("Calibri", java.awt.Font.BOLD, 12));
    }

    private void jmItemCursivaActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtaEditor.setFont(new java.awt.Font("Calibri", java.awt.Font.ITALIC, 12));
    }

    private void jmItemSubrayadoActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtaEditor.setFont(new java.awt.Font("Calibri", java.awt.Font.PLAIN, 12));
    }

    private void jmItemSinEstiloActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtaEditor.setFont(new java.awt.Font("Calibri", java.awt.Font.PLAIN, 12));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jfrmG2U3().setVisible(true));
    }

    private javax.swing.JMenuItem Predeterminada;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmItem10;
    private javax.swing.JMenuItem jmItem12;
    private javax.swing.JMenuItem jmItem14;
    private javax.swing.JMenuItem jmItem16;
    private javax.swing.JMenuItem jmItem20;
    private javax.swing.JMenuItem jmItem24;
    private javax.swing.JMenuItem jmItemAzul;
    private javax.swing.JMenuItem jmItemCopiar;
    private javax.swing.JMenuItem jmItemCortar;
    private javax.swing.JMenuItem jmItemCursiva;
    private javax.swing.JMenuItem jmItemF;
    private javax.swing.JMenuItem jmItemNegrita;
    private javax.swing.JMenuItem jmItemNegro;
    private javax.swing.JMenuItem jmItemPegar;
    private javax.swing.JMenuItem jmItemRojo;
    private javax.swing.JMenuItem jmItemSalir;
    private javax.swing.JMenuItem jmItemSinEstilo;
    private javax.swing.JMenuItem jmItemSubrayado;
    private javax.swing.JMenuItem jmItemVerde;
    private javax.swing.JMenuItem jmItemX;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbtCopiar;
    private javax.swing.JButton jbtCortar;
    private javax.swing.JButton jbtPegar;
    private javax.swing.JTextArea jtxtaEditor;
}
