
import java.awt.Font;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ladpa
 */
public class jfrmG2U3 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jfrmG2U3.class.getName());

    /**
     * Creates new form jfrmG2U3
     */
    public jfrmG2U3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jbtCortar = new javax.swing.JButton();
        jbtCopiar = new javax.swing.JButton();
        jbtPegar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtaEditor = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jmItemSalir = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmItemCortar = new javax.swing.JMenuItem();
        jmItemCopiar = new javax.swing.JMenuItem();
        jmItemPegar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jmItemF = new javax.swing.JMenuItem();
        jmItemX = new javax.swing.JMenuItem();
        Predeterminada = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jbtCortar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tijeras.png"))); // NOI18N
        jbtCortar.setToolTipText("Cortar");
        jbtCortar.setFocusable(false);
        jbtCortar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtCortar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtCortar.addActionListener(this::jbtCortarActionPerformed);
        jToolBar1.add(jbtCortar);

        jbtCopiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pegar.png"))); // NOI18N
        jbtCopiar.setToolTipText("Copiar");
        jbtCopiar.setFocusable(false);
        jbtCopiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtCopiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtCopiar.addActionListener(this::jbtCopiarActionPerformed);
        jToolBar1.add(jbtCopiar);

        jbtPegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/guardar.png"))); // NOI18N
        jbtPegar.setToolTipText("Pegar");
        jbtPegar.setFocusable(false);
        jbtPegar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtPegar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtPegar.addActionListener(this::jbtPegarActionPerformed);
        jToolBar1.add(jbtPegar);

        jtxtaEditor.setColumns(20);
        jtxtaEditor.setRows(5);
        jScrollPane1.setViewportView(jtxtaEditor);

        jMenu2.setText("Archivo");

        jmItemSalir.setText("Salir");
        jmItemSalir.addActionListener(this::jmItemSalirActionPerformed);
        jMenu2.add(jmItemSalir);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Edicion");

        jmItemCortar.setText("Cortar");
        jmItemCortar.addActionListener(this::jmItemCortarActionPerformed);
        jMenu1.add(jmItemCortar);

        jmItemCopiar.setText("Copiar");
        jmItemCopiar.addActionListener(this::jmItemCopiarActionPerformed);
        jMenu1.add(jmItemCopiar);

        jmItemPegar.setText("Pegar");
        jmItemPegar.addActionListener(this::jmItemPegarActionPerformed);
        jMenu1.add(jmItemPegar);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Opciones");

        jMenu4.setText("Fuente");

        jmItemF.setText("Arial");
        jmItemF.setToolTipText("");
        jmItemF.addActionListener(this::jmItemFActionPerformed);
        jMenu4.add(jmItemF);

        jmItemX.setText("Courier new");
        jmItemX.addActionListener(this::jmItemXActionPerformed);
        jMenu4.add(jmItemX);

        Predeterminada.setText("Predeterminada");
        Predeterminada.addActionListener(this::PredeterminadaActionPerformed);
        jMenu4.add(Predeterminada);

        jMenu3.add(jMenu4);

        jMenu5.setText("Tamaño");

        jMenuItem1.setText("jMenuItem1");
        jMenu5.add(jMenuItem1);

        jMenu3.add(jMenu5);

        jMenu6.setText("Color de fuente");
        jMenu3.add(jMenu6);

        jMenu7.setText("Estilo de fuente");
        jMenu3.add(jMenu7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtCortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCortarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jbtCortarActionPerformed

    private void jbtCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCopiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtCopiarActionPerformed

    private void jbtPegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPegarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtPegarActionPerformed

    private void jmItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmItemSalirActionPerformed

    private void jmItemCortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemCortarActionPerformed
        // TODO add your handling code here:
        jtxtaEditor.cut();
    }//GEN-LAST:event_jmItemCortarActionPerformed

    private void jmItemCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemCopiarActionPerformed
        // TODO add your handling code here:
        jtxtaEditor.copy();
    }//GEN-LAST:event_jmItemCopiarActionPerformed

    private void jmItemPegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemPegarActionPerformed
        // TODO add your handling code here:
        jtxtaEditor.paste();
    }//GEN-LAST:event_jmItemPegarActionPerformed

    private void jmItemFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemFActionPerformed
        // TODO add your handling code here:
        jtxtaEditor.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 12));
    }//GEN-LAST:event_jmItemFActionPerformed

    private void jmItemXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemXActionPerformed
        // TODO add your handling code here:
        jtxtaEditor.setFont(new java.awt.Font("Courier New", java.awt.Font.BOLD, 12));
    }//GEN-LAST:event_jmItemXActionPerformed

    private void PredeterminadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PredeterminadaActionPerformed
        // TODO add your handling code here:
        jtxtaEditor.setFont(new java.awt.Font("Calibri", java.awt.Font.BOLD, 12));
    }//GEN-LAST:event_PredeterminadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jfrmG2U3().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Predeterminada;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbtCopiar;
    private javax.swing.JButton jbtCortar;
    private javax.swing.JButton jbtPegar;
    private javax.swing.JMenuItem jmItemCopiar;
    private javax.swing.JMenuItem jmItemCortar;
    private javax.swing.JMenuItem jmItemF;
    private javax.swing.JMenuItem jmItemPegar;
    private javax.swing.JMenuItem jmItemSalir;
    private javax.swing.JMenuItem jmItemX;
    private javax.swing.JTextArea jtxtaEditor;
    // End of variables declaration//GEN-END:variables
}
